import { NestFactory } from '@nestjs/core';
import { SwaggerModule, DocumentBuilder } from '@nestjs/swagger';
import { AppModule } from './app.module';
import { ValidationPipe } from '@nestjs/common/pipes';
// import metadata from './metadata'; // <-- file auto-generated by the "PluginMetadataGenerator"

async function bootstrap() {
  const app = await NestFactory.create(AppModule);

  const config = new DocumentBuilder()
    .setTitle('Prueba concepto Osos')
    .setDescription('Descripción de API de osos')
    .setVersion('1.0')
    .addTag('osos')
    .build();

  // await SwaggerModule.loadPluginMetadata(metadata); // <-- here

  const document = SwaggerModule.createDocument(app, config);
  SwaggerModule.setup('api', app, document);
  
  app.enableCors();
  app.useGlobalPipes(new ValidationPipe({
    transform: true,
    enableDebugMessages:true
  }));
  await app.listen(4000);
}
bootstrap();
